import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./prodect_detail/prodect_detail.css";
import "./orders/Order.css"
import "./order_detail/order_detail.css"
import "./car/car.css"
import "./profile/profile.css"
import {ThemProvider} from './hooks/ThemProvider'
import {Header , Footer , Settings ,Snack_bar} from "./components/home";
import { cookies } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const access = cookieStore.get("access")?.value;
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ThemProvider>
          <header>
            <Header token_access={access}/>
          </header>
          <Snack_bar/>
          {children}
        </ThemProvider>
        <footer>
          <Footer/>
        </footer>
        <Settings/>
      </body>
    </html>
  );
}
