import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./prodect_detail/prodect_detail.css";
import "./orders/Order.css"
import "./order_detail/order_detail.css"
import "./car/car.css"
import "./profile/profile.css"
import {Login_info} from '../app/hooks/Login'
import {Header , Footer , Settings} from "./components/home";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Login_info>
          <header>
            <Header/>
          </header>
          {children}
          <footer>
            <Footer/>
          </footer>
          <Settings/>
        </Login_info>
      </body>
    </html>
  );
}
