import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import "../globals.css";
import "./prodect_detail/prodect_detail.css";
import "./orders/Order.css";
import "./car/car.css";
import "./shop/shop.css";
import "./order_form/order_form.css";
import { ThemProvider } from "../hooks/ThemProvider";
import { OrderProvider } from "../hooks/order_hooks";
import { Header, Footer, Snack_bar } from "../components/home";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { locales } from "../config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!locales.includes(locale)) {
    notFound();
  }
  setRequestLocale(locale);
  const cookieStore = await cookies();
  const access = cookieStore.get("access")?.value;
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemProvider>
            <header>
              <Header token_access={access} />
            </header>
            <Snack_bar />
            <OrderProvider>{children}</OrderProvider>
          </ThemProvider>
          <footer>
            <Footer />
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
